export const FETCH_FACULTIES_SUCCESS = "FETCH_FACULTIES_SUCCESS";
export const FETCH_FACULTIES_FAILURE = "FETCH_FACULTIES_FAILURE";
export const INCREMENT = "INCREMENT";
export const DECREMENT = "DECREMENT";
